# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 901b7927bb6ca2f3a3f62eb470e5a8ef341852daca851623a837d05e976888d31e331e51f52307102a65ee8467b62271ad14d6916d66f6f2462710ee5216b77b

test:
  secret_key_base: d82ee4f8a0eb72488808d8f9cabcbb4e07645ca79c63c9e298c9c43dfa471041682b7849ec6d213cc8a36717dcfcf0acb8bdbd0403326df291aa98c3b1acf469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
